<SplashScreen>:
    canvas.before:
        Color:
            rgba: 0, 0, 0, 1
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: "vertical"
        padding: dp(40)
        spacing: dp(20)

        Widget:

        Image:
            source: "assets/icon.png"
            size_hint: (None, None)
            size: dp(180), dp(180)
            pos_hint: {"center_x": 0.5}

        Label:
            text: "Tune"
            font_size: "48sp"
            color: 1, 1, 1, 1
            size_hint_y: None
            height: dp(70)
            pos_hint: {"center_x": 0.5}

        Label:
            text: "Твоя музыка всегда с тобой"
            font_size: "16sp"
            color: 0.55, 0.55, 0.68, 1
            size_hint_y: None
            height: dp(30)
            pos_hint: {"center_x": 0.5}

        Widget:

        Label:
            text: "Загрузка..."
            font_size: "14sp"
            color: 0.55, 0.55, 0.68, 1
            size_hint_y: None
            height: dp(30)
            pos_hint: {"center_x": 0.5}

        Widget:
